<?php
/**
 * @var $block \Firebear\PlatformM1\Block\Adminhtml\Migration\Shell
 */
?>

<div class="col-sm-6 col-sm-offset-3">
    <!-- OUR FORM -->
    <form class="form command-form" id="form" data-mage-init='{"validation": {}}' action="#" method="POST">

        <input type="hidden" name="form_key" value="<?php echo $block->getFormKey(); ?>" />

        <div id="path-group" class="admin__field field field-title  required _required">
            <label class="label admin__field-label" for="path"><?php echo __('Path of Magento Root Directory'); ?></label>
            <input type="text"
                   class="command-input required-entry input-text admin__control-text required-entry _required"
                   data-validate="{required:true}"
                   name="path"
                   placeholder="<?php echo 'e.g. ' . BP; ?>" />
            <!-- errors will go here -->
        </div>

        <div class="form-group">
            <div class="base-path">
                <span class="label-text"><?php echo __('Your Magento Root Path'); ?> : </span>
                <span class="path"><?php echo BP; ?></span>
                <span><a id="use-path" val="<?php echo BP; ?>" href="#"><?php echo __('Use') ?></a></span>
            </div>
        </div>

        <div id="command-group" class="form-group" style="margin-top: 20px;">
            <label class="label admin__field-label" for="command"><?php echo __('Command'); ?></label>
            <select name="command" class="status required-entry _required select admin__control-select" data-validate="{required:true}" id="command">
                <option value="">--- Select Command ---</option>
                <optgroup label="Migration">
                    <option value="bin/magento firebear:migrate --entity=CmsBlocks">Cms Block</option>
                    <option value="bin/magento firebear:migrate --entity=CmsPages">Cms Page</option>
                    <option value="bin/magento firebear:migrate --entity=Categories">Categories</option>
                    <option value="bin/magento firebear:migrate --entity=ProductAttributes">Product Attributes</option>
                    <option value="bin/magento firebear:migrate --entity=Products">Products</option>
                    <option value="bin/magento firebear:migrate --entity=ProductsMedia">Media Links Rewrite</option>
                    <option value="bin/magento firebear:migrate --entity=Inventory">Catalog Inventory</option>
                    <option value="bin/magento firebear:migrate --entity=Customers">Customers</option>
                    <option value="bin/magento firebear:migrate --entity=Quotes">Quotes</option>
                    <option value="bin/magento firebear:migrate --entity=Orders">Orders</option>
                    <option value="bin/magento firebear:migrate --entity=Shipments">Shipments</option>
                    <option value="bin/magento firebear:migrate --entity=ProductReviews">Product Reviews</option>
                    <option value="bin/magento firebear:migrate --entity=Invoices">Invoices</option>
                    <option value="bin/magento firebear:migrate --entity=Creditmemo">CreditMemos</option>
                    <option value="bin/magento firebear:migrate --entity=Catalogrule">Catalog rules</option>
                    <option value="bin/magento firebear:migrate --entity=CustomerGroup">Customer Groups</option>
                    <option value="bin/magento firebear:migrate --entity=Tax">Taxes</option>
                    <option value="bin/magento firebear:migrate --entity=TaxOrderAggregated">Taxes Order Aggregated</option>
                    <option value="bin/magento firebear:migrate --entity=SalesRule">Sales Rules</option>
                    <option value="bin/magento firebear:migrate --entity=Wishlist">Wishlist</option>
                    <option value="bin/magento firebear:migrate --entity=NewsletterSubscribers">Newsletter Subscribers</option>
                </optgroup>
                <optgroup label="Indexer">
                    <option value="bin/magento indexer:reindex">ReIndexer</option>
                </optgroup>
                <optgroup label="Cache">
                    <option value="bin/magento cache:status">Status</option>
                    <option value="bin/magento cache:flush">Flush</option>
                </optgroup>
            </select>
        </div>

        <button type="submit" class="primary"><?php echo __('Run'); ?> <span class="fa fa-arrow-right"></span></button>

    </form>
    <div class="console-container">
        <div title="Close" class="close-btn sys-btn"><i class="fa fa-close"></i></div>
        <div title="Minimize" class="minimize-btn sys-btn"><i class="fa fa-minus"></i></div>
        <div title="Reload" id="reload-btn" class="reload-btn sys-btn"><i class="fa fa-refresh"></i></div>
        <div class="console" >
            <div class="result-content">
                <div class="command-text">
                    <span class="user">TCT</span>&nbsp;:<span class="path" id="path"></span>&nbsp;$&nbsp;&nbsp;
                    <span class="command" id="command-display"></span>
                </div>
                <div id="alert-success">

                </div>
            </div>

        </div>
    </div>

</div>
<!-- put form validaiton -->
<script type="text/x-magento-init">
{
    "#form": {
    	"validation": {}
    }
}
</script>

<script>
    require(['jquery'],function($){
        jQuery(document).ready(function() {
            jQuery('#form').submit(function(event) {
                $('.form-group').removeClass('has-error');
                $('.help-block').remove();
                var path = $('input[name=path]').val();
                var command = $('select[name=command]').val();

                if (path.length && command.length) {
                    var formData = {
                        'path' : path,
                        'command' 	: command
                    };
                    var ajaxUrl = "<?php echo $block->getFormActionUrl(); ?>";
                    $.ajax({
                        type 		: 'POST',
                        url 		: ajaxUrl,
                        data 		: formData,
                        dataType 	: 'json',
                        encode 		: true,
                        showLoader	: true,
                        success    : function (data) {
                            $("#alert-success").html(data.message);
                            $("#alert-success").removeClass('hidden');
                            window.location.href = '';
                        },
                        error     : function (err) {
                            if (err.errors.path) {
                                $('#path-group').addClass('has-error');
                                $('#path-group').append('<div class="help-block">' + err.errors.path + '</div>');
                            }
                            if (err.errors.command) {
                                $('#command-group').addClass('has-error');
                                $('#command-group').append('<div class="help-block">' + err.errors.command + '</div>');
                            }
                        }
                    });
                }
                event.preventDefault();
            });
        });
    });
</script>
